const express = require('express')
const router = express.Router()
const user = require('./modules/user')
const movie = require('./modules/movie')
const home = require('./modules/home')
const favorite = require('./modules/favorite')
const comment = require('./modules/comments')
const { authenticator } = require('../middleware/auth')

router.use('/movies', movie)
router.use('/users', user)
router.use('/comments', comment)
router.use('/favorite', authenticator, favorite)
router.use('/', home)
module.exports = router
